project:
  type: website
  output-dir: submitted

website:
  title: "OEKA201AssignmentMMO2"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    toc: true
    toc-depth: 3
    Mainfont: "Arial"
    Font size: 1.2
    Line stretch: 1.5

  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    Mainfont: "Times"
    colorlinks: true
    lof: true
    lot: true

  docx:
    toc: true
    toc-depth: 3

  epub:
    toc: true
    toc-depth: 3
    Mainfont: "Verdana"


bibliography: ref.bib


